name: Deploy

on:
  push:
    branches: ["main"]

concurrency:
  group: "deployments"
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      PUBLIC_SITE_REPOSITORY: ${{ secrets.PUBLIC_REPOSITORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'
      - name: Build
        run: |
          npm ci
          npm run build
          echo '👍 BUILT SUCESSFULLY'
      - name: Checkout Public Repository
        run: |
          echo '👍 THE SITE IS BUILT—PUSHING IT BACK TO GITHUB-PAGES'
          export REPO_NAME=`echo "$GITHUB_REPOSITORY" | cut -d "/" -f 2`
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.PUBLIC_DEPLOY_KEY }}'
          git clone git@github.com:${PUBLIC_SITE_REPOSITORY}.git public_site
          echo `Current: $pwd`
          rm -rfv "public_site/${REPO_NAME}" && \
          mkdir -pv "public_site/${REPO_NAME}" && \
          mv -v dist/* "public_site/${REPO_NAME}/"
      - name: Deploy
        run: |
          echo "👍 Committing to public repo ${PUBLIC_SITE_REPOSITORY}"
          export REPO_NAME=`echo "$GITHUB_REPOSITORY" | cut -d "/" -f 2`
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.PUBLIC_DEPLOY_KEY }}'
          pushd public_site && \
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add . && \
          echo -n 'Files to Commit:' && ls -l | wc -l && \
          git commit -m "Deploy $GITHUB_REPOSITORY to /$REPO_NAME" && \
          git push --force && \
          popd && \
          rm -rf ${PUBLIC_SITE_REPOSITORY}
          echo '👍 GREAT SUCCESS!'
